### ISSUE TITLE
Update photos of speakers

### ISSUE THREAD

**Issue by dbelob** [JugruGroup/guess-game#12]
## Overview
Replace photos with others with better quality, requirements for them:
- _JPG_ format
- aspect ratio: 1:1
- maximum size: 400px x 400px
## Implementation
- [x] Check speaker picture files in the [directory](https://github.com/JugruGroup/guess-game/tree/master/guess-game-web/src/assets/images/speakers)
- [x] Create a bad photo list
- [x] Replace with better photos

**Comment by ugliansky** [comment]
Список тех, кому искали фотку получше, но не нашли:

1. 0195.jpg Светлана Исакова, Joker 2015 (University day)

2. 0199.jpg Alexey Vishentsev, JPoint 2014

3. 0204.jpg Alexander Otenko, Joker 2013

4. 0205.jpg Kuzma Deretuk, Joker 2013

5. 0212.jpg Anya Barski, JPoint 2013

6. 0215.jpg Vitaly Trifanov, JPoint

7. 0216.jpg Alexander Makarov, JPoint

8. 0238.jpg Kirill Klensky, jug.ru

9. 0245.jpg Dmitry Kozorez, jug.ru

10. 0270.jpg Roman Udovichenko, TechTrain 

11. 0314.jpg Evgeny Gorodov, JBreak

12. 0316.jpg Igor Tyazhev, JBreak

13. 0335.jpg Valentin Ziegler, CppRussia

14. 0337.jpg Alexander Granin, CppRussia (ну ладно, фокту Гранина можно было найти, но самая нормальная у него - маленькая)

15. 0345.jpg Sergey Sadovnikov, CppRussia

16. 0347.jpg Kirill Tihonov, CppRussia

17. 0349.jpg Anton Dunchev, CppRussia

18. 0350.jpg Aergey Fedorov, CppRussia

19. 0351.jpg Pavel Novikov, CppRussia

20. 0352.jpg Ilya Bogdanov, CppRussia

21. 0354.jpg Alexander Schmidt, CppRussia

22. 0355.jpg Javier Garcia Sogo, CppRussia 

23 0357.jpg Alexander Voronkov, Cpp Russia

**Comment by dbelob** [comment]
Photos updated:
0143.jpg Philipp Krenn, DevOops 2019
0508.jpg Hadi Hariri, DevOops 2019
0852.jpg Vladimir Ivanov, DevOops 2019

**Comment by dbelob** [comment]
I propose to close the task.
